"""add unique subscription constraint

Revision ID: 4ccc10fdb716
Revises: ae64dbe08113
Create Date: 2026-08-26 15:00:56.239444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccc10fdb716'
down_revision: Union[str, Sequence[str], None] = 'ae64dbe08113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscriber_author', 'subscriptions', ['subscriber_id', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subscriber_author', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
